### ISSUE TITLE
 Failed to resolve directive: scroll (found in component: <mycomponent>)

### ISSUE THREAD

**Issue by appodeepa** [wangpin34/vue-scroll#3] opened 2016-09-10 09:42 UTC
Hi,

Followed the instructions exactly as outlined and this isn't working. Instead see the above error.

Any ideas?

**Comment by wangpin34** [comment] 2016-09-27 09:09
Can you share code on-line ?

**Comment by wangpin34** [comment] 2016-10-21 02:06
Close this issue cause no further details provided.

**Comment by xerosanyam** [comment] 2017-02-15 13:32
Getting the same error.
````
import vuescroll from 'vue-scroll'
export default {
 components: {
    'v-scroll': vuescroll // or just vuescroll tried both
   }
}
````

**Comment by wangpin34** [comment] 2017-03-06 02:34
@xerosanyam  Did you [use the plugin](https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin) at the very beginning?

```
import Vue from 'vue'
import vuescroll from 'vue-scroll'

Vue.use(vuescroll)
```

**Comment by Edmund1645** [comment] 2019-08-01 21:27
I used 

> @xerosanyam Did you [use the plugin](https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin) at the very beginning?
> 
> ```
> import Vue from 'vue'
> import vuescroll from 'vue-scroll'
> 
> Vue.use(vuescroll)
> ```

I used this same exact method and it worked like twice and then it stopped.

What I just noticed is that it takes time to initialize.

**Comment by wangpin34** [comment] 2019-08-02 07:08
@Edmund1645 I had created a demo on codesandbox: https://codesandbox.io/s/vuescroll-demo-orders-view-f4d3d?fontsize=14. Please go ahead and check what's the differences in your project. Anyway, it's better to have your code which can reproduce the error online for me to check. Good luck, :).

**Comment by Edmund1645** [comment] 2019-08-02 15:15
@wangpin34 I checked the demo and I'm pretty sure I did everything correctly, the documentation is well detailed. I noticed that the scrolling works when I navigate to another route and return back.
code snippets below: 
```javascript
import Vue from 'vue';
import App from './App.vue';
import router from './router';
import VueScrollTo from 'vue-scrollto';
import locomotiveScroll from 'locomotive-scroll';

Vue.config.productionTip = false;

new Vue({
  router,
  render: h => h(App)
}).$mount('#app');

Vue.use(VueScrollTo, {
  easing: 'ease-out'
});
const scroll = new locomotiveScroll();

```
This is a snippet of how I initialize vueScroll.

**Comment by Edmund1645** [comment] 2019-08-02 15:17
I see the problem, the correct way to initialize vueScroll was to do it before initializing the vue  instance.
like this: 
```javascript
import Vue from 'vue';
import App from './App.vue';
import router from './router';
import VueScrollTo from 'vue-scrollto';
import locomotiveScroll from 'locomotive-scroll';

Vue.config.productionTip = false;
Vue.use(VueScrollTo, {
  easing: 'ease-out'
}); // this comes first

new Vue({
  router,
  render: h => h(App)
}).$mount('#app');

const scroll = new locomotiveScroll();
```

**Comment by wangpin34** [comment] 2019-08-03 08:23
@Edmund1645  Glad to know the problem been resolved. And, I have checked the vuejs docs at [here](https://vuejs.org/v2/guide/plugins.html). It said
> Use plugins by calling the Vue.use() global method. This has to be done before you start your app by calling new Vue()

I'm considering if it's better to add this notice in the readme of vue-scroll as well since it truly blocks some guys.

**Closed as completed by wangpin34** 2019-08-03 08:23 UTC
Labels: help wanted

**Comment by akinhwan** [comment] 2019-12-02 02:28
wow thanks, didn't realize i had all my Vue.use() until after the new Vue declaration
